##########################
## Site Config Settings ##
##########################

# Theme version
version: 2.0.1

# Header
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

# Sidebar
widgets:
  - recent_posts
  - category
  - tag
  - archive
  #- weibo
  - links

# Toc
toc:
  enable: false
  number: false

# Static files
js: js
css: css

# Date_formats
date_formats:
  archive: "MM月DD日"
  category: "YYYY/MM/DD"
  post: "MMM DD, YYYY"
  tag: "YYYY/MM/DD"

# Extensions
Plugins:
  hexo-generator-feed
  hexo-generator-sitemap
  hexo-generator-baidu-sitemap

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#Local search
local_search: true ## Use a javascript-based local search engine, true/false.

#Cmments
comment:
  duoshuo: #chaooo ## duoshuo_shortname
  disqus: ## disqus_shortname
  livere: ## 来必力(data-uid)
  # uyan: 2147918
  cloudTie: ## 网易云跟帖(productKey)
  changyan: ## 畅言需在下方配置两个参数，此处不填。
    appid: cytrKUm6t
    appkey: a6e3132eb1e5e6ebd63f9871f9af8809
    
#Share
baidu_share: ## 百度分享
JiaThis_share: ##true ##JiaThis分享
duoshuo_share: #true ##true 多说分享必须和多说评论一起使用。
addToAny_share: # AddToAny share. Empty list hides. List items are service name at url. For ex: email for '<a href="https://www.addtoany.com/add_to/email?linkurl=...'
#  - twitter
#  - baidu
#  - facebook
#  - google_plus
#  - linkedin
#  - email

# Analytics
google_analytics: UA-139320825-1 ## Your Google Analytics tracking id, e.g. UA-42025684-2
baidu_analytics: 767e3ea52a6b4f3c656cdd4119c87e62 ## Your Baidu Analytics tracking id, e.g. 1006843030519956000

# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.

# About page
about:
  photo_url:  ## Your photo e.g. http://obzf7z93c.bkt.clouddn.com/themeauthor.jpg
  items:
  - label: 电子邮件
    url: 
    title: hudi@linuxmail.org; admin@hudi.site

  - label: qq
    url: 
    title: 120165907

  - label: 通信地址
    url: 
    title: 安徽省合肥市包河区花园大道8号合肥工业大学智能制造技术研究院，230000


  # - label: github
  #   url: ## Your github'url e.g.  https://github.com/chaooo
  #   title: ## Your github'name e.g.  chaooo
  # - label: weibo
  #   url: ## Your weibo's url e.g.  http://weibo.com/zhengchaooo
  #   title: ## Your weibo's name e.g.  秋过冬漫长
# - label: twitter
#   url: 
#   title:
# - label: facebook
#   url:
#   title:

# Links widget. Empty links will hide widget.
links:
  - title: 所有VB API的源码
    url: https://github.com/slacker-HD/creo_vbapi
    
  - title: 所有WebLink的源码
    url: https://github.com/slacker-HD/creo_weblink

  - title: 所有Toolkit的源码
    url: https://github.com/slacker-HD/creo_toolkit

  - title: 所有Jlink的源码
    url: https://github.com/slacker-HD/creo_jlink

  - title: WebLink工具（仅在Creo内置浏览器打开）
    url: https://weblink.hudi.site/
  # - title: site-name2
  #   url: http://www.example2.com/
  # - title: site-name3
  #   url: http://www.example3.com/
highlight:
  enable: true
  auto_detect: true
  line_number: true
  tab_replace: